### ISSUE TITLE
Mention VTK DLLs in Readme

### ISSUE THREAD

**Issue by eliemichel** [tkarabela/MfxVTK#1]
Super nice, builds nicely! :) I am actually thrilled to run an effect written by somebody else than myself. ^^

I think you could just precise to either add the bin directory of VTK's build to the `PATH` or copy the appropriate dll/so files next to the .ofx:
![image](https://user-images.githubusercontent.com/5802849/95887383-0cffd580-0d80-11eb-9338-c5c27d5c4e28.png)

PS: Also aren't they missing from the release zip/tarball you provided?

**Comment by tkarabela** [comment]
Oh, this should be documented better. You can actually get rid of the runtime dependency if you use `BUILD_SHARED_LIBS=OFF` when building VTK, then it will put everything into the compiled .ofx shared library when building MfxVTK. The binaries I uploaded to GitHub are made this way, eg. for the Linux one I get:

```
$ ldd libmfx_vtk_plugin-0.2.0.ofx
	linux-vdso.so.1 (0x00007fffa65ff000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007effa121c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007effa11f9000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007effa1018000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007effa0ec9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007effa0eae000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007effa0cbc000)
	/lib64/ld-linux-x86-64.so.2 (0x00007effa21fa000)
```

I've tried the Windows 0.2.0 binary on another computer and they seem to be doing fine without the DLLs. Can you do a clean build of VTK with `BUILD_SHARED_LIBS=OFF` on your machine as well? :) If it solves the issue, I'll clarify that in the readme and close the ticket.

**Comment by eliemichel** [comment]
I confirm it works!

PS: I shared you repo on twitter, hope you don't mind! https://twitter.com/exppad/status/1316067551269588992
