### ISSUE TITLE
Input geometry seems wrong with the point sampler

### ISSUE THREAD

**Issue by eliemichel** [tkarabela/MfxVTK#2]
On a simple example, with a cube, a subsurface modifier, then the *Point sampling* effect from MfxVTK:

![image](https://user-images.githubusercontent.com/5802849/95887072-b6929700-0d7f-11eb-99d0-37b2b9355f79.png)

![image](https://user-images.githubusercontent.com/5802849/95887089-babeb480-0d7f-11eb-808c-df6aaba2e0d3.png)

Didn't see any problem with the other effects at first glance!

**Comment by tkarabela** [comment]
Thanks for testing and the bug report! This filter apparently doesn't like non-planar faces, so I added triangulation to get around this. It doesn't interfere with sampling of edges, which works on the original mesh.

![Screenshot from 2020-10-14 21-06-06](https://user-images.githubusercontent.com/8166544/96038600-a35af680-0e67-11eb-91b3-03e242115d2e.png)
