### ISSUE TITLE
Simplify reference to OpenMeshEffect in CMakeLists

### ISSUE THREAD

**Issue by eliemichel** [tkarabela/MfxVTK#8]
Hi Tomáš,

FYI you may now just `add_subdirectory(OpenMeshEffect)` rather than diving into the subdirectories like here: ;)

https://github.com/tkarabela/MfxVTK/blob/70e5d7d3ff8e52c8adc3c68860af541b13490a14/src/CMakeLists.txt#L24

**Comment by tkarabela** [comment]
Nice change from a library writer point of view! :)

I've implemented it in 306a912902ea658140bcd11cfcbe5a88f6efe043, but I needed https://github.com/eliemichel/OpenMeshEffect/pull/13 to get it working.
